version: '2'

services:

  php7_app:
    image: "ezsystems/php:7.0-v1"
    links:
      - "mysql_db:mysql"
    volumes:
      - "./ezplatform:/var/www/html/ezplatform"
    networks:
      - backend

  nginx_web:
    image: "nginx:stable"
    volumes:
      - "./ezplatform:/var/www/html/ezplatform"
    ports:
      - "8080:80"
    links:
      - php7_app
    networks:
      - backend
    environment:
      - SYMFONY_ENV
      - MAX_BODY_SIZE=20
      - FASTCGI_PASS=php7_app:9000
      - TIMEOUT=190
      - DOCKER0NET
    command: /bin/bash -c "cd /var/www/html/ezplatform && cp -a doc/nginx/ez_params.d /etc/nginx && bin/vhost.sh --template-file=doc/nginx/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ezplatform
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
