version: '2'

services:

  php:
    extends:
      file: "services/php.yml"
      service: "php56_fpm"
    links:
      - "db"
    volumes:
      - "./ezplatform:/var/www/html/ezplatform"
    networks:
      - backend

  web:
    extends:
      file: "services/web.yml"
      service: "apache_php56"
    volumes:
      - "./ezplatform:/var/www/html/ezplatform"
    networks:
      - backend
    links:
      - "php"
    ports:
      - "80:80"

  db:
    extends:
      file: "services/db.yml"
      service: "mysql"
    networks:
      - backend
    expose:
      - "3306"

networks:
  backend:
