version: '2.1'

services:

  php:
    extends:
      file: "services/php.yml"
      service: "${DOCKER_PHP:-php56_fpm}"
    links:
      - "db"
    volumes:
      - "./ezplatform:/var/www/html/ezplatform"
    networks:
      - backend

  web:
    extends:
      file: "services/web.yml"
      service: "${DOCKER_WEB:-apache_php56}"
    volumes:
      - "./ezplatform:/var/www/html/ezplatform"
    networks:
      - backend
    links:
      - "php"
    ports:
      - "80:80"

  db:
    extends:
      file: "services/db.yml"
      service: "${DOCKER_DB:-mysql}"
    networks:
      - backend
    expose:
      - "3306"

networks:
  backend:
